### ISSUE TITLE
todo's from todos.txt

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#70]
I deleted the todo's .txt. 

Relevant actionable todo's:
 
- [ ] Clean up local files from mlrng
- [ ] Clean up todo files from normal mlr
- [ ] Clean up R6 Interface
- [ ] `affect.cols` is nice, we might want to write PipeOp's that affect only numerics etc.
- [ ] Do we want to have an option to store intermediate results

**Comment by berndbischl** [comment]
needs to  be transformed into clean issues

**Comment by berndbischl** [comment]
this need to be converted issues
